Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_2/hls4ml_prj/keras_model.keras'
OutputDir: model_2/hls4ml_prj
OutputPredictions: null
Part: xc7a200tsbg484-1
ProjectName: myproject
Stamp: 456eabb3
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
