Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_3.1/hls4ml_prj/keras_model.keras'
OutputDir: model_3.1/hls4ml_prj
OutputPredictions: null
Part: xc7a200tsbg484-1
ProjectName: myproject
Stamp: 9ad530be
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
